IN-5409：スプレッドシートの情報をaxiosで取得して表示
indigonote/sti-temporary-readdb-training-yamasaki pull request #1
Opened 2024-07-04 06:30 UTC by YamasakiKei-sti

# 概要(Overview)

公開されているスプレッドシートの情報を取得

## チケットリンク(Ticket Link)

ex. **スプレッドシートの情報を取得**
https://sios-tech.atlassian.net/jira/software/projects/IN/boards/2?assignee=712020%3Ad2465931-0b65-4c68-a646-5bf71f5e89fb&selectedIssue=IN-5409

### 原因(任意)

- 特になし

## 実装したこと(Actions taken)

- axiosでスプレッドシートの情報を取得、console.logで結果を出力

## 実装しないことにしたもの(Actions not taken)

- 特になし

# PRレビユーについて

## PRレビュアへの共有事項

- 環境変数とdocker-compose.ymlを変更しております
- スプレッドシートの中身が人によって異なっていると思います

## PRレビュー観点
- 正しい挙動をしているのか、よくない書き方をしていないかレビューしてほしいです

# テストについて

### 動作確認(Operation confirmation)

- ターミナルでデータを取得できている

## 影響する機能(Affected features)

- 特になし

## このPRで必要になる動作確認

- コマンドでの確認のみ

### デプロイ後の動作確認について

- 無し

## その他(任意)

2024-07-04 07:18 UTC, m-sato-sios-com commented on app/src/IN-5409/index.ts
> +main()
ファイル末尾には改行を入れてください

2024-07-04 07:20 UTC, m-sato-sios-com commented on app/src/IN-5409/index.ts
行末にセミコロンを入れてください

2024-07-04 08:05 UTC, uehara requested changes

2024-07-04 08:05 UTC, uehara commented on .env
> +USER_CSV_URL = 'https://docs.google.com/spreadsheets/d/e/2PACX-1vRrFHXduXTsN21JfIzgfjiL9do_UUaRFai9ZwzpgP5y1CxfmEIe_S0EDJlCx5Rax7O6VwWijdSnUtCX/pub?output=csv'
urlをenvのしたのは良いね

2024-07-04 08:05 UTC, uehara commented on app/prisma/migrations/20240702071311_init/migration.sql
> +CREATE UNIQUE INDEX "users_email_key" ON "users"("email");
インデックス作ったのは素晴らしい

2024-07-04 08:05 UTC, uehara commented on app/prisma/migrations/20240702071311_init/migration.sql
> +ALTER TABLE "Post" ADD CONSTRAINT "Post_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE CASCADE;
外部キーもいいね

2024-07-04 08:05 UTC, uehara commented on app/prisma/schema.prisma
> +  posts         Post[]
prsmak
リレーションも作ってるのはすごいね

2024-07-04 08:05 UTC, uehara commented on app/src/IN-5409/index.ts
> +  const userSpreadSheet = process.env.USER_CSV_URL
型を明示しよう、そして、undefinedの可能性もあるので考慮を

2024-07-04 08:22 UTC, kousuke-nagata-sti approved these changes

2024-07-04 08:24 UTC, m-sato-sios-com approved these changes

2024-07-04 08:27 UTC, YamasakiKei-sti commented on app/src/IN-5409/index.ts
行末のセミコロンを追加しました。

2024-07-04 08:41 UTC, Haruki-Hosokawa-sti commented on app/src/IN-5409/index.ts
> +  } catch {
```
try {
  hoge
} catch (error) {
  console.error('スプレッドシートの読み込みに失敗、errorMessage:', error.message);
}
```

のようにerrorを受け取ったらいいと思います。
型を確認しないとerrorになると思うので、確認できるようにしてみてください。

2024-07-05 00:18 UTC, YamasakiKei-sti commented on app/src/IN-5409/index.ts
> +  const userSpreadSheet = process.env.USER_CSV_URL
変数の型を明示しました。

2024-07-05 01:58 UTC, YamasakiKei-sti commented on app/src/IN-5409/index.ts
> +  } catch {
catch部分でerrorを受け取るように修正しました。

2024-07-10 06:16 UTC, uehara approved these changes

2024-07-10 06:48 UTC, Haruki-Hosokawa-sti approved these changes

2024-07-10 06:53 UTC, Haruki-Hosokawa-sti approved these changes

2024-07-12 02:28 UTC, merged